// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oxpudzapcjbqlykewskg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im94cHVkemFwY2picWx5a2V3c2tnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwMDYzODgsImV4cCI6MjA1ODU4MjM4OH0.zwJrXlZRxN7nEk5zvJOKjjxfwCq6g_2yggZVpoUShZ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});